name: ocrrub
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_ml_kit: ^0.7.3
  provider: ^6.0.1
  edge_detection:
    path: ./.edge_detection-1.0.8/
  pretty_diff_text: ^1.0.0
  auto_size_text: ^3.0.0
  string_similarity: ^2.0.0
  screenshot: ^1.2.3
  path_provider: ^2.0.8
  file_picker: ^4.3.1
  csv: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
